server:
  port: 8080

spring:
  application:
    name: helpage
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 400MB # 最大支持文件大小
      max-request-size: 400MB # 最大支持请求大小

# mybatis配置
# mybatis:
#   mapper-locations: classpath:mapper/*.xml
